name: Haskell CI

on:
  push:
    branches: '**'
  pull_request:
    branches-ignore: '**'

# Stop other CI in the same branch on new run:
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

# Some Haskell tools are preinstalled in: `/usr/local/.ghcup`.
# There's a symlink: `~/.ghcup` -> `/usr/local/.ghcup`.

jobs:
  build:
    name: Build (GHC ${{ matrix.ghc-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc-version: ['9.8.4']

        # include:
        #   - os: windows-latest
        #     ghc-version: '9.8'
        #   - os: macos-latest
        #     ghc-version: '9.8'

    steps:
      - uses: actions/checkout@v4

      # ------------------------------------------------------------
      # Setup GHC
      # ------------------------------------------------------------
      # TODO: Separate setup-verify and verify from build and test, merge build and test

      - name: Restore GHC ${{ matrix.ghc-version }}
        uses: actions/cache/restore@v4
        id: ghc-cache
        with:
          path: |
            ~/.ghcup/ghc/${{ matrix.ghc-version }}/bin
            ~/.ghcup/ghc/${{ matrix.ghc-version }}/lib/ghc-${{ matrix.ghc-version }}/bin
            ~/.ghcup/ghc/${{ matrix.ghc-version }}/lib/ghc-${{ matrix.ghc-version }}/lib
          key: _GHC_${{ runner.os }}-ghc-${{ matrix.ghc-version }}

      - name: Set GHC path
        if: steps.ghc-cache.outputs.cache-hit == 'true'
        run: |
          echo "$HOME/.ghcup/ghc/${{ matrix.ghc-version }}/bin" >> "$GITHUB_PATH"
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
          ghc --version
          cabal --version
          cabal path

      # I don't want to install Cabal with haskell-actions@setup, so:
      - name: Pre downloading GHC ${{ matrix.ghc-version }}
        if: steps.ghc-cache.outputs.cache-hit != 'true'
        run: mv /usr/local/.ghcup/bin/cabal{,-old}

      - name: Download GHC ${{ matrix.ghc-version }}
        uses: haskell-actions/setup@v2
        if: steps.ghc-cache.outputs.cache-hit != 'true'
        id: setup
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: "3.10" # dummy, to not match to the preinstalled version

      - name: Post downloading GHC ${{ matrix.ghc-version }}
        if: steps.ghc-cache.outputs.cache-hit != 'true'
        run: mv /usr/local/.ghcup/bin/cabal{-old,}

      - name: Inspect
        run: |
          ls -lA ~/
          ls -lA /usr/local
          which ghc
          ghc --version
          cabal --version
          cabal path

      - name: Save GHC cache
        uses: actions/cache/save@v4
        if: steps.ghc-cache.outputs.cache-hit != 'true'
        with:
          # It contains unnecessary files though
          path: |
            ~/.ghcup/ghc/${{ matrix.ghc-version }}/bin
            ~/.ghcup/ghc/${{ matrix.ghc-version }}/lib/ghc-${{ matrix.ghc-version }}/bin
            ~/.ghcup/ghc/${{ matrix.ghc-version }}/lib/ghc-${{ matrix.ghc-version }}/lib
          key: ${{ steps.ghc-cache.outputs.cache-primary-key }}

      - name: Configure the build
        run: |
          cabal update
          cabal configure --enable-tests --enable-benchmarks --disable-documentation
          cabal build all --dry-run
        # The last step generates dist-newstyle/cache/plan.json for the cache key.

      - name: Restore cached dependencies
        uses: actions/cache/restore@v4
        id: deps-cache
        env:
          key: ${{ runner.os }}-ghc-${{ matrix.ghc-version }}
        with:
          path: ~/.local/state/cabal/store
          key: dist-${{ env.key }}-plan-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ env.key }}-

      - name: Install dependencies
        # If we had an exact cache hit, the dependencies will be up to date.
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: cabal build all --only-dependencies

      - name: Save dependency cache
        uses: actions/cache/save@v4
        # If we had an exact cache hit, trying to save the cache would error because of key clash.
        if: steps.deps-cache.outputs.cache-hit != 'true'
        with:
          path: ~/.local/state/cabal/store
          key: ${{ steps.deps-cache.outputs.cache-primary-key }}

      # TODO: Maybe clear the cache if it got too fat
      - name: Restore cached ac-lbrary-hs
        uses: actions/cache/restore@v4
        id: lib-cache
        env:
          key: ${{ runner.os }}-ghc-${{ matrix.ghc-version }}
        with:
          path: dist-newstyle
          key: ac-library-hs-${{ github.run_id }}-${{ env.key }}

      - name: Build ac-library-hs
        run: cabal build lib:ac-library-hs

      - name: Save cached ac-library-hs
        uses: actions/cache/save@v4
        env:
          key: ${{ runner.os }}-ghc-${{ matrix.ghc-version }}
        with:
          path: dist-newstyle
          key: ac-library-hs-${{ github.run_id }}-${{ env.key }}

  test:
    needs: build
    name: Test (GHC ${{ matrix.ghc-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    # TODO: DRY
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc-version: ['9.8.4']

        # include:
        #   - os: windows-latest
        #     ghc-version: '9.8'
        #   - os: macos-latest
        #     ghc-version: '9.8'
    steps:
      # ------------------------------------------------------------
      # Setup Haskell (TODO: move to a separate composite action file)
      # ------------------------------------------------------------
      - uses: actions/checkout@v4

      - name: Restore GHC ${{ matrix.ghc-version }}
        uses: actions/cache/restore@v4
        id: ghc-cache
        with:
          fail-on-cache-miss: true
          path: |
            ~/.ghcup/ghc/${{ matrix.ghc-version }}/bin
            ~/.ghcup/ghc/${{ matrix.ghc-version }}/lib/ghc-${{ matrix.ghc-version }}/bin
            ~/.ghcup/ghc/${{ matrix.ghc-version }}/lib/ghc-${{ matrix.ghc-version }}/lib
          # TODO: use hash for caching
          key: _GHC_${{ runner.os }}-ghc-${{ matrix.ghc-version }}

      - name: Set GHC path
        if: steps.ghc-cache.outputs.cache-hit == 'true'
        run: |
          echo "$HOME/.ghcup/ghc/${{ matrix.ghc-version }}/bin" >> "$GITHUB_PATH"
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
          which ghc
          ghc --version
          cabal --version
          cabal path

      # I don't want to install Cabal with haskell-actions@setup, so:
      - name: Pre downloading GHC ${{ matrix.ghc-version }}
        if: steps.ghc-cache.outputs.cache-hit != 'true'
        run: mv /usr/local/.ghcup/bin/cabal{,-old}

      - name: Download GHC ${{ matrix.ghc-version }}
        uses: haskell-actions/setup@v2
        if: steps.ghc-cache.outputs.cache-hit != 'true'
        id: setup
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: "3.10" # dummy, to not match to the preinstalled version

      - name: Post downloading GHC ${{ matrix.ghc-version }}
        if: steps.ghc-cache.outputs.cache-hit != 'true'
        run: mv /usr/local/.ghcup/bin/cabal{-old,}

      - name: Inspect
        run: |
          which ghc
          ghc --version
          cabal --version
          cabal path

      - name: Configure the build
        run: |
          cabal update
          cabal configure --enable-tests --enable-benchmarks --disable-documentation
          cabal build all --dry-run
        # The last step generates dist-newstyle/cache/plan.json for the cache key.

      - name: Restore cached dependencies from the `build` job
        uses: actions/cache/restore@v4
        id: deps-cache
        env:
          key: ${{ runner.os }}-ghc-${{ matrix.ghc-version }}
        with:
          fail-on-cache-miss: true
          path: ~/.local/state/cabal/store
          key: dist-${{ env.key }}-plan-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ env.key }}-

      - name: Restore cached `ac-lbrary-hs` from the `build` job
        uses: actions/cache/restore@v4
        id: lib-cache
        env:
          key: ${{ runner.os }}-ghc-${{ matrix.ghc-version }}
        with:
          fail-on-cache-miss: true
          path: dist-newstyle
          key: ac-library-hs-${{ github.run_id }}-${{ env.key }}

      # ------------------------------------------------------------
      # Run tests
      # ------------------------------------------------------------
      - name: Build check
        # make sure to build all the components in `ac-library-hs.cabal` (TODO: automate this)
        run: |
          cabal build ac-library-hs
          cabal build ac-library-hs:example-lazy-segtree
          cabal build ac-library-hs:ac-library-hs-benchmark

      - name: Run tests
        run: cabal test all

      - name: Run doctest
        run: |
          cabal install doctest
          cabal repl --with-ghc=doctest --repl-options='-w -Wdefault'

      - name: Check cabal file
        run: cabal check

      # - name: Build documentation
      #   run:
      #     cabal haddock all --disable-documentation
      #     # --disable-documentation disables building documentation for dependencies.
      #     # The package's own documentation is still built,
      #     # yet contains no links to the documentation of the dependencies.

  # Run oj-verify in 20 tasks
  verify:
    needs: build
    name: Verify (GHC 9.8.4 on ubuntu-latest)
    runs-on: ubuntu-latest
    env:
      ghc-version: '9.8.4'
    strategy:
      fail-fast: false
      matrix:
        parallel-index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
        ghc-version: ['9.8.4']

    steps:
      # ------------------------------------------------------------
      # Setup Haskell (TODO: move to a separate composite action file)
      # ------------------------------------------------------------
      - uses: actions/checkout@v4

      - name: Restore GHC ${{ matrix.ghc-version }}
        uses: actions/cache/restore@v4
        id: ghc-cache
        with:
          fail-on-cache-miss: true
          path: |
            ~/.ghcup/ghc/${{ matrix.ghc-version }}/bin
            ~/.ghcup/ghc/${{ matrix.ghc-version }}/lib/ghc-${{ matrix.ghc-version }}/bin
            ~/.ghcup/ghc/${{ matrix.ghc-version }}/lib/ghc-${{ matrix.ghc-version }}/lib
          key: _GHC_${{ runner.os }}-ghc-${{ matrix.ghc-version }}

      - name: Set GHC path
        if: steps.ghc-cache.outputs.cache-hit == 'true'
        run: |
          echo "$HOME/.ghcup/ghc/${{ matrix.ghc-version }}/bin" >> "$GITHUB_PATH"
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
          ghc --version
          cabal --version
          cabal path

      # I don't want to install Cabal with haskell-actions@setup, so:
      - name: Pre downloading GHC ${{ matrix.ghc-version }}
        if: steps.ghc-cache.outputs.cache-hit != 'true'
        run: mv /usr/local/.ghcup/bin/cabal{,-old}

      - name: Download GHC ${{ matrix.ghc-version }}
        uses: haskell-actions/setup@v2
        if: steps.ghc-cache.outputs.cache-hit != 'true'
        id: setup
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: "3.10" # dummy, to not match to the preinstalled version

      - name: Post downloading GHC ${{ matrix.ghc-version }}
        if: steps.ghc-cache.outputs.cache-hit != 'true'
        run: mv /usr/local/.ghcup/bin/cabal{-old,}

      - name: Inspect
        run: |
          which ghc
          ghc --version
          cabal --version
          cabal path

      - name: Configure the build
        run: |
          cabal update
          cabal configure --enable-tests --enable-benchmarks --disable-documentation
          cabal build all --dry-run
        # The last step generates dist-newstyle/cache/plan.json for the cache key.

      - name: Restore cached dependencies from the `build` job
        uses: actions/cache/restore@v4
        id: deps-cache
        env:
          key: ${{ runner.os }}-ghc-${{ matrix.ghc-version }}
        with:
          fail-on-cache-miss: true
          path: ~/.cabal/store
          key: dist-${{ env.key }}-plan-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ env.key }}-

      - name: Restore cached `ac-lbrary-hs` from the `build` job
        uses: actions/cache/restore@v4
        id: lib-cache
        env:
          key: ${{ runner.os }}-ghc-${{ matrix.ghc-version }}
        with:
          fail-on-cache-miss: true
          path: dist-newstyle
          key: ac-library-hs-${{ github.run_id }}-${{ env.key }}

      # ------------------------------------------------------------
      # Run verification test
      # ------------------------------------------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install oj-verify
        run: pip3 install -U online-judge-verify-helper

      # TODO: cache `~/.cache/online-judge-tools/library-checker-problems/`
      # TODO: cache `.verify-helper/cache/`

      - name: Run oj-verify
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        #   GH_PAT: ${{ secrets.GH_PAT }}
        working-directory: verify
        run: |
          files="$(find app/ -type f | awk 'NR % 20 == ${{ matrix.parallel-index }}')"
          echo 'target files:'
          for f in $files ; do
            echo "- $f"
          done
          oj-verify run $files --tle 30 -j $(nproc)
